cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from orders.views import paymenthandler

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('paymenthandler/', paymenthandler, name='paymenthandler'),
    path('0cd7a23f-55ba-4901-a665-e667a74e05ee/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/',views.admin_order_detail,name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf,name='admin_order_pdf'),
]

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1,widget=forms.NumberInput(attrs={'min': 1, 'max': 100}))
    override = forms.BooleanField(initial=False, required=False, widget=forms.HiddenInput)


class MessageForm(forms.Form):
    name = forms.CharField(
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Your Name'
        })
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Your Email'
        })
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Your Message',
            'rows': 5
        })
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
 
 cart = Cart(request)
 product = get_object_or_404(Product, id=product_id)
 form = CartAddProductForm(request.POST)
 
 if form.is_valid():
    cd = form.cleaned_data
    cart.add(product=product,
        quantity=cd['quantity'],
        override_quantity=cd['override'])
    
 return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
 cart = Cart(request)
 for item in cart:
    item['update_quantity_form'] = CartAddProductForm(initial={
    'quantity': item['quantity'],
    'override': True})
 return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block content %}
    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">
      <!-- Mobile Nav (max width 767px)-->
      <div class="mobile-nav">
        <!-- Navbar Brand -->
        <div class="amado-navbar-brand">
          <a href="/"
            ><img src="{% static 'img/core-img/logo.png' %}" alt=""
          /></a>
        </div>
        <!-- Navbar Toggler -->
        <div class="amado-navbar-toggler">
          <span></span><span></span><span></span>
        </div>
      </div>

      <!-- Header Area Start -->
      <header class="header-area clearfix">
        <!-- Close Icon -->
        <div class="nav-close">
          <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <!-- Logo -->
        <div class="logo">
          <a href="/"
            ><img src="{% static 'img/core-img/logo.png' %}" alt=""
          /></a>
        </div>
        <!-- Amado Nav -->
        <nav class="amado-nav">
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/shop">Shop</a></li>
            <li class="active"><a href="/cart">Cart</a></li>
            <li ><a href="/feedback">Feedback</a></li>
            <li ><a href="/contact">Contact Us</a></li>
          </ul>
        </nav>
        <!-- Button Group -->
        {% comment %} <div class="amado-btn-group mt-30 mb-100">
          <a href="#" class="btn amado-btn mb-15">%Discount%</a>
          <a href="#" class="btn amado-btn active">New this week</a>
        </div> {% endcomment %}
        <!-- Cart Menu -->
        <div class="cart-fav-search mb-100">
          <a href="/cart" class="cart-nav"
            ><img src="{% static 'img/core-img/cart.png' %}" alt="" /> Cart
            <span>({{ cart|length }})</span></a
          >
          {% comment %} <a href="#" class="fav-nav"
            ><img src="{% static 'img/core-img/favorites.png' %}" alt="" />
            Favourite</a
          > {% endcomment %}
          <a href="#" class="search-nav"
            ><img src="{% static 'img/core-img/search.png' %}" alt="" />
            Search</a
          >
        </div>
        <!-- Social Button -->
        {% comment %} <div class="social-info d-flex justify-content-between">
          <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
          <a href="https://www.instagram.com/goodluck_florist/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
          <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
          <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
        </div> {% endcomment %}
      </header>
      <!-- Header Area End -->

      <div class="cart-table-area section-padding-100">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12 col-lg-8">
              <div class="cart-title mt-50">
                <h2>Shopping Cart</h2>
              </div>

              <div class="cart-table clearfix">
                <table class="table table-responsive">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Name</th>
                      <th>Price</th>
                      <th>Quantity</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in cart %}
                      {% with product=item.product %}
                      <tr>
                        <td class="cart_product_img">
                          <a href="{{ product.get_absolute_url }}"
                            ><img
                              src="{{ product.image.url }}"
                              alt="Product"
                          /></a>
                        </td>
                        <td class="cart_product_desc">
                          <h5>{{ product.name }}</h5>
                        </td>
                        <td class="price">
                          <span style="font-size: 14px;">₹{{ item.total_price }}</span>
                        </td>
                        <td class="qty">
                          <div class="qty-btn d-flex">
                            <div class="quantity">
                              <form action="{% url "cart:cart_add" product.id %}" method="post">
                                 {{ item.update_quantity_form.quantity }}
                                 {{ item.update_quantity_form.override }}
                                 <input type="submit" value="Update" style="font-size: 12px;background: white;font-style: bold;">
                                 {% csrf_token %}
                              </form>
                            </div>
                          </div>
                        </td>
                        <td>
                          <form class="quantity" action="{% url "cart:cart_remove" product.id %}" method="post">
                            <input type="submit" value="Remove" style="font-size: 12px;border: none;background: white;font-style: bold;">
                            {% csrf_token %}
                         </form>
                        </td>
                      </tr>
                      {% endwith %}
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
            <div class="col-12 col-lg-4">
              <div class="cart-summary">
                <h5>Cart Total</h5>
                <ul class="summary-table">
                  <li><span>subtotal:</span> <span>₹{{ cart.get_product_price }}</span></li>
                  <li><span>delivery:</span> <span>₹{{ cart.get_delivery_charge }}</span></li>
                  <li><span>total:</span> <span>₹{{ cart.get_total_price }}</span></li>
                </ul>
                <div class="cart-btn mt-100">
                  <a href="{% url "orders:order_create" %}" class="btn amado-btn w-100">Checkout</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

{% endblock content %}