cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from orders.views import paymenthandler

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('paymenthandler/', paymenthandler, name='paymenthandler'),
    path('0cd7a23f-55ba-4901-a665-e667a74e05ee/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('feedback/', views.feedback, name='feedback'),
    path('search/', views.post_search, name='post_search'),
    path('shop/', views.product_list, name='product_list'),
    path('contact/', views.contact_page, name='contact_page'),
    path('policies/', views.policies_page, name='policies_page'),
    path('product/review/', views.review_form,name='product_review'),
    path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
    path('googleb0dbb8bde61b8b0b.html/', views.verify, name='gsc_verification'),
    path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator,MinValueValidator


# Create your models here.
class CoreCategory(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Core categories'
    
    def __str__(self):
        return self.name


class Category(models.Model):
    core_category = models.ForeignKey(CoreCategory,on_delete=models.CASCADE, related_name='subcategories')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args= [self.slug])
    

    class Meta: 
        ordering = ['name',]
        indexes = [
            models.Index(fields=['name']),
        ]

        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
        
    def count(self):
        return Product.objects.filter(category=self).count()

class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id,self.slug])

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id','slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
    
    def __str__(self):
        return self.name
    

class ProductImage(models.Model):
    name = models.CharField(max_length=30)
    product = models.ForeignKey(Product,related_name='images',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='reviews')
    created = models.DateTimeField(auto_now_add=True)
    body = models.TextField(null=False)
    rating = models.IntegerField(choices=[
        (1,'Terrible'),
        (2,'poor'),
        (3,'Average'),
        (4,'Good'),
        (5,'Excellent'),
    ],default=5,
    validators=[MaxValueValidator(5),MinValueValidator(1)])

    class Meta:
        ordering = ['-created']


class SiteReviewModel(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    body = models.TextField(null=False)
    rating = models.IntegerField(choices=[
        (1,'Terrible'),
        (2,'poor'),
        (3,'Average'),
        (4,'Good'),
        (5,'Excellent'),
    ],default=5,
    validators=[MaxValueValidator(5),MinValueValidator(1)])

    class Meta:
        ordering = ['-created']

shop/forms.py
from django import forms
from .models import ProductReview,SiteReviewModel

class ReviewForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        fields = ['product','body','rating']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Hide the 'product' field by using the HiddenInput widget
        self.fields['product'].widget = forms.HiddenInput()
    
class SiteReviewForm(forms.ModelForm):
    
    class Meta:
        model = SiteReviewModel
        fields = ['body','rating']
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['body'].widget.attrs.update({'class': 'mx-3'})

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Product,Category,SiteReviewModel,CoreCategory
from cart.forms import CartAddProductForm, MessageForm
from django.contrib.postgres.search import SearchRank,SearchVector,SearchQuery
from .forms import ReviewForm,SiteReviewForm
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.mail import send_mail
from .tasks import sendmessage

# Create your views here.

def product_list(request,category_slug=None):
    page_number = request.GET.get('page', 1)
    category = None
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        products = Product.objects.filter(category=category)
    else:
        products = Product.objects.filter(available=True)
    
    total_product_count = Product.objects.all().count()
    paginator = Paginator(products,4)
    categories = Category.objects.all()
    core_categories = CoreCategory.objects.all()
    cart_product_form = CartAddProductForm()
    products = paginator.get_page(page_number)

    return render(request,'shop/product/list.html',
                            {'category': category,
                            'categories': categories,
                            'core_categories': core_categories,
                            'products': products,
                            'total_product_count': total_product_count,
                            'page_product_count': len(products),
                            'cart_product_form': cart_product_form})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
    id=id,
    slug=slug)
    form = ReviewForm({"product":product,
                       "rating":(5,'Excellent'),})
    return render(request,
    'shop/product/detail.html',
    {'product': product,
    'form':form})


def home(request):
   try:
        products = Product.objects.all()[:6]
   except IndexError:
        products = Product.objects.all()

   return render(request,'shop/home.html',{'products':products})

def verify(request):
    return render(request,'shop/googleb0dbb8bde61b8b0b.html')

def contact_page(request):
    message_form = MessageForm()
    if request.method == 'POST':
        message_form = MessageForm(request.POST)
        if message_form.is_valid():
            # Extract data from form
            cd = message_form.cleaned_data
            email = cd['email']
            subject = f"Message from {cd['name']} at Goodluck Florist"
            message_body = f"Name: {cd['name']}\nEmail: {cd['email']}\n\nMessage:\n{cd['message']}"
            
            sendmessage.delay(subject,message_body,email)
            
            messages.success(request, "Your message has been sent successfully!")
        else:
            messages.error(request, "There was an error with your form. Please correct it and try again.")

    return render(request, 'shop/contactus.html', {"form": message_form})

def policies_page(request):
    return render(request,'shop/policies.html')


def post_search(request):
    query = None
    results = []
    
    if 'search' in request.GET:
        query = request.GET.get('search')
        print(query)
        search_vector = SearchVector('name')
        search_query = SearchQuery(query)

        results = Product.objects.annotate(
            search=search_vector,
            rank=SearchRank(search_vector, search_query)
        ).filter(search=search_query).order_by('-rank')
        print(results)
    return render(request, 'shop/search.html', {
        'query': query,
        'results': results,
    })

@require_POST
def review_form(request):
    form = ReviewForm(request.POST)
    referring_url = request.META.get('HTTP_REFERER', '/')
    if form.is_valid():
        form.save()
        messages.success(request,"review submitted")
    else:
        messages.error(request,'review not valid')
    return redirect(referring_url)

def feedback(request):

    reviews_count = SiteReviewModel.objects.all().count()
    if reviews_count>5:
        reviews = SiteReviewModel.objects.all()[:5]
    else:
        reviews = SiteReviewModel.objects.all()
    if request.method == "POST":
        form = SiteReviewForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Feedback submitted')
            return redirect(request.META.get('HTTP_REFERER', '/'))

        else:
            messages.error(request,'Failed to submit the Feedback')
            return render(request,'shop/feedback.html',{'form':form,
                                                'reviews':reviews})
    form = SiteReviewForm()
    return render(request,'shop/feedback.html',{'form':form,
                                                'reviews':reviews})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>{% block title %}{% endblock title %}</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}" />

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'css/core-style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
      <div class="search-close">
        <i class="fa fa-close" aria-hidden="true"></i>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="search-content">
              <form action="{% url "shop:post_search" %}" method="get">
                <input
                  type="search"
                  name="search"
                  id="search"
                  placeholder="Type your keyword..."
                />
                <button type="submit">
                  <img src="{% static 'img/core-img/search.png' %}" alt="" />
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Search Wrapper Area End -->
    
    {% block content %}
        {% block message %}
          {% if messages %}
          <ul id="messages_box" class="messages">
              {% for message in messages %}
                  {% if message.tags == 'error' %}
                    <div class="alert alert-danger alert-dismissible fade show custom-alert" role="alert">
                      {{message}}
                      <strong class="killAlert" style="float: right;cursor: pointer;">&times;</strong>
                    </div>
                  {% else %}
                    <div class="alert alert-{{message.tags}} alert-dismissible fade show custom-alert" role="alert">
                      {{message}}
                      <strong class="killAlert" style="float: right;cursor: pointer;">&times;</strong>
                    </div>
                  {% endif %}
              {% endfor %}
          </ul>
          {% endif %}
        {% endblock message %}

    {% endblock content %}
  
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
      <div class="container">
        <div class="row align-items-center">
          <!-- Single Widget Area -->
          <div class="col-12 col-lg-4">
            <div class="single_widget_area">
              <!-- Logo -->
              <div class="footer-logo mr-50">
                <a href="/"
                  ><img src="{% static 'img/core-img/logo2.png' %}" alt=""
                /></a>
              </div>
              <!-- Copywrite Text -->
              <p class="copywrite">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script>
                All rights reserved | This template is made with
                <i class="fa fa-heart-o" aria-hidden="true"></i> by
                <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->&
                Re-distributed by
                <a href="https://themewagon.com/" target="_blank">Themewagon</a>
              </p>
            </div>
          </div>
          <!-- Single Widget Area -->
          <div class="col-12 col-lg-8">
            <div class="single_widget_area">
              <!-- Footer Menu -->
              <div class="footer_menu">
                <nav class="navbar navbar-expand-lg justify-content-end">
                  <button
                    class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#footerNavContent"
                    aria-controls="footerNavContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                  >
                    <i class="fa fa-bars"></i>
                  </button>
                  <div class="collapse navbar-collapse" id="footerNavContent">
                    <ul class="navbar-nav ml-auto">
                      <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="/shop">Shop</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="/cart">Cart</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="/feedback">Feedback</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="/contact">Contact Us</a>
                      </li>
                    </ul>
                  </div>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="{% static 'js/customjs.js' %}"></script>

    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
  </body>
</html>

shop/templates/shop/contactus.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Contact Us{% endblock %}

{% block content %}
<!-- ##### Main Content Wrapper Start ##### -->
<div class="main-content-wrapper d-flex clearfix">

    <!-- Mobile Nav (max width 767px)-->
    <div class="mobile-nav">
        <!-- Navbar Brand -->
        <div class="amado-navbar-brand">
            <a href="/"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
        </div>
        <!-- Navbar Toggler -->
        <div class="amado-navbar-toggler">
            <span></span><span></span><span></span>
        </div>
    </div>

    <!-- Header Area Start -->
    <header class="header-area clearfix">
        <!-- Close Icon -->
        <div class="nav-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <!-- Logo -->
        <div class="logo">
            <a href="/"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
        </div>
        <!-- Amado Nav -->
        <nav class="amado-nav">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/shop">Shop</a></li>
                <li><a href="/cart">Cart</a></li>
                <li ><a href="/feedback">Feedback</a></li>
                <li class="active"><a href="/contact">Contact Us</a></li>
            </ul>
        </nav>
        <!-- Button Group -->
        {% comment %} <div class="amado-btn-group mt-30 mb-100">
            <a href="#" class="btn amado-btn mb-15">%Discount%</a>
            <a href="#" class="btn amado-btn active">New this week</a>
        </div> {% endcomment %}
        <!-- Cart Menu -->
        <div class="cart-fav-search mb-100">
            <a href="/cart" class="cart-nav"><img src="{% static 'img/core-img/cart.png' %}" alt=""> Cart <span>({{ cart|length }})</span></a>
            {% comment %} <a href="#" class="fav-nav"><img src="{% static 'img/core-img/favorites.png' %}" alt=""> Favourite</a> {% endcomment %}
            <a href="#" class="search-nav"><img src="{% static 'img/core-img/search.png' %}" alt=""> Search</a>
        </div>
        <!-- Social Button -->
        <div class="social-info d-flex justify-content-between">
            {% comment %} <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
            <a href="https://www.instagram.com/goodluck_florist/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a> {% endcomment %}
        </div>
    </header>
    <!-- Header Area End -->

    <!-- ##### Contact Area Start ##### -->
    <div class="single-product-area section-padding-100 clearfix">
        <div class="container">
            {% block message %}
                {{ block.super }}
            {% endblock message %}
            <div class="row">
                <!-- Policies Link Section -->
                <div class="col-12">
                    <h1 class="mb-3">
                        <a href="/policies" class="text-decoration-none text-primary" style="font-size: 2rem;">
                            Our Policies
                        </a>
                    </h1>
                </div>

                <!-- Contact Info -->
                <div class="col-12 col-lg-6">
                    <div class="contact-info">
                        <h2>Contact Information</h2>
                        <p>
                            If you have any questions or need further assistance, feel free to contact us using the form below or reach us via our contact details.
                        </p>
                        <ul class="contact-details">
                            <li>
                                <i class="fa fa-map-marker" aria-hidden="true"></i> Good Luck Florist, Lower Parel, Mumbai, India
                            </li>
                            <li>
                                <i class="fa fa-phone" aria-hidden="true"></i> +91 9820487222
                            </li>
                            <li>
                                <i class="fa fa-envelope" aria-hidden="true"></i> goodluckflorist@gmail.com
                            </li>
                        </ul>
                    </div>
                </div>


            <!-- Contact Form Section -->
            <div class="col-12 col-lg-6">
                <div class="contact-form">
                    <h2>Send Us a Message</h2>
                    <form action="{% url 'shop:contact_page' %}" method="post" novalidate>
                        {% csrf_token %}
                        <div class="row">
                            <!-- Name Field -->
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    {{ form.name }}
                                </div>
                            </div>

                            <!-- Email Field -->
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    {{ form.email }}
                                </div>
                            </div>

                            <!-- Message Field -->
                            <div class="col-12">
                                <div class="form-group">
                                    {{ form.message }}
                                </div>
                            </div>

                            <!-- Submit Button -->
                            <div class="col-12">
                                <button type="submit" class="btn amado-btn mb-15">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            </div>

            <!-- Google Map -->
            <div class="row">
                <div class="col-12">
                    <div class="google-map">
                        <iframe 
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3773.287553795499!2d72.8289996!3d18.9986034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7ce8d3425563d%3A0x221a73958bb7c38e!2sGood+Luck+Florist+Lower+Parel+Mumbai!5e0!3m2!1sen!2sin!4v1712877636533!5m2!1sen!2sin" 
                            width="100%" 
                            height="450" 
                            style="border:0;" 
                            allowfullscreen="" 
                            loading="lazy">
                        </iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Contact Area End ##### -->
</div>
<!-- ##### Main Content Wrapper End ##### -->
{% endblock %}

shop/templates/shop/feedback.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Contact Us{% endblock %}
{% load shop_tags %}
{% block content %}
<!-- ##### Main Content Wrapper Start ##### -->
<div class="main-content-wrapper d-flex clearfix">

    <!-- Mobile Nav (max width 767px)-->
    <div class="mobile-nav">
        <!-- Navbar Brand -->
        <div class="amado-navbar-brand">
            <a href="/"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
        </div>
        <!-- Navbar Toggler -->
        <div class="amado-navbar-toggler">
            <span></span><span></span><span></span>
        </div>
    </div>

    <!-- Header Area Start -->
    <header class="header-area clearfix">
        <!-- Close Icon -->
        <div class="nav-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <!-- Logo -->
        <div class="logo">
            <a href="/"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
        </div>
        <!-- Amado Nav -->
        <nav class="amado-nav">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/shop">Shop</a></li>
                <li><a href="/cart">Cart</a></li>
                <li class="active" ><a href="/feedback">Feedback</a></li>
                <li><a href="/contact">Contact Us</a></li>
            </ul>
        </nav>
        <!-- Button Group -->
        {% comment %} <div class="amado-btn-group mt-30 mb-100">
            <a href="#" class="btn amado-btn mb-15">%Discount%</a>
            <a href="#" class="btn amado-btn active">New this week</a>
        </div> {% endcomment %}
        <!-- Cart Menu -->
        <div class="cart-fav-search mb-100">
            <a href="/cart" class="cart-nav"><img src="{% static 'img/core-img/cart.png' %}" alt=""> Cart <span>({{ cart|length }})</span></a>
            {% comment %} <a href="#" class="fav-nav"><img src="{% static 'img/core-img/favorites.png' %}" alt=""> Favourite</a> {% endcomment %}
            <a href="#" class="search-nav"><img src="{% static 'img/core-img/search.png' %}" alt=""> Search</a>
        </div>
        <!-- Social Button -->
        <div class="social-info d-flex justify-content-between">
            {% comment %} <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
            <a href="https://www.instagram.com/goodluck_florist/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a> {% endcomment %}
        </div>
    </header>
    <!-- Header Area End -->

    <!-- ##### Contact Area Start ##### -->
    <div class="single-product-area section-padding-100 clearfix">
        <div class="container">
            {% block message %}
                {{ block.super }}
            {% endblock message %}
            <!-- Policies and Terms Section -->
             <div class="row mx-3 mt-4">
                <div class="container">
                    <p>We Value Your Feedback
                        At Good Luck Florist, we’re passionate about providing beautiful flowers and exceptional service. Your feedback is incredibly important to us and helps us improve our offerings to serve you better. Whether you’ve recently made a purchase, received an order, or just have thoughts to share, we would love to hear from you!</p>
                </div>
                <div class="col-12" style="display: flex;justify-content: center;">
                    <div class="contact-form">
                        <form action="{% url 'shop:feedback' %}" method="post">
                            {% csrf_token %}
                                <p class="mb-1 mt-3">Feedback :</p>
                                {{ form.body }}
                                <p class="mb-1 mt-3">Experience :</p>
                                {{ form.rating }}
                                <button class="btn btn-primary mx-3">submit</button>
                        </form>
                    </div>
                </div>
                
             </div>

                  <!-- Reviews Section -->
            <div class="row mt-5">
                <div class="col-12">
                    <h4>Customer Reviews</h4>
                    <div class="reviews">
                        {% if reviews %}
                        {% for review in reviews.all %}
                        <div class="media mb-4">
                            <img class="mr-2 rounded-circle" src="{% static 'img/core-img/user.jpg' %}" alt="User image" style="width: 60px; height: 60px;">
                            <div class="media-body">
                                <span>{{ review.body }}</span>
                                <div class="ratings-review" style="color: gold;">
                                    <div class="ratings">
                                    {% for i in review.rating|rangeOf %}
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        {% endfor %}
                                    </div>
                                </div>
                                <small class="text-muted">Posted on {{ review.created|date:"F j, Y, g:i a" }}</small>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}<p>No reviews yet. Be the first to review this product!</p>
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- ##### Contact Area End ##### -->
</div>
<!-- ##### Main Content Wrapper End ##### -->
{% endblock %}

shop/templates/shop/googleb0dbb8bde61b8b0b.html
google-site-verification: googleb0dbb8bde61b8b0b.html